before:
  hooks:
    - go mod tidy
builds:
- goos:
    - linux
  goarch:
    - 386
    - amd64
    - arm
    - arm64
  goarm:
    - 7
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
