---
name: gotest
on: ["push", "pull_request"]

jobs:
  gotest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: WillAbides/setup-go-faster@v1.7.0
        with:
          go-version: 1.17

      - name: Test Go Code
        run: "go test ./..."

      - name: Run Go Vet
        run: "go vet ./..."

      - name: Run StaticCheck
        uses: dominikh/staticcheck-action@v1.1.0
        with:
          version: "2021.1.1"
          install-go: false
